name: SistemaCdaZombies
main: com.avelar.Main
version: 1.3.5
depend: [ArzioLib]
softdepend: [Vault]

commands:
  customzombies:
    aliases: [cz]
    description: Reload do SistemaCdaZombies

permissions:
  customzombies.admin:
    default: op
